GET http://127.0.0.1:4800/user-api/users

###
POST http://127.0.0.1:4800/user-api/users
Content-Type: application/json

{
    "userId":201,
    "name":"Vin",
    "age":20
}

###
PUT http://127.0.0.1:4800/user-api/users
Content-Type: application/json

{
    "userId":201,
    "name":"Vini",
    "age":21
}

### Read a user by id
GET http://localhost:4800/user-api/users/201


###
DELETE http://127.0.0.1:4800/user-api/users/202


###
GET http://127.0.0.1:4800/product-api/products

###
POST http://127.0.0.1:4800/product-api/products
Content-Type: application/json

{
    "productId":101,
    "name":"TV",
    "price":50000,
    "brand":"sony"
}

###
PUT http://127.0.0.1:4800/product-api/products
Content-Type: application/json

{
    "productId":101,
    "name":"laptop",
    "price":60000,
    "brand":"dell"
}

### Read a user by id
GET http://localhost:4800/product-api/products-productId/102

### Read products by brand
GET http://localhost:4800/product-api/products-brand/sony


###
DELETE http://127.0.0.1:4800/product-api/products/102